server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: leyou-user
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  #redis配置
  redis:
    #redis数据库编号，存在0-15共16个数据库
    database: 0
    #redis服务号IP
    host: 127.0.0.1
    #redis端口号
    port: 6379
    #redis密码（我系统的redis没有设置密码）
    #password: xxx
    #redis请求超时时间，超过此值redis自动断开连接
    timeout: 10000ms
    #jedis配置
    jedis:
      pool:
        #jedis最大连接数，超过此值则提示获取不到连接异常
        max-active: 32
        #jedis最大等待时间，超过此值会提示连接超时异常
        max-wait: 10000ms
        #jedis最大等待连接数
        max-idle: 32
        #jedis最小等待连接数
        min-idle: 0
